#!/usr/bin/env python3
"""RainHedge: deploy to Studionet + honest live consensus smoke.

Record-porting architecture: pins point at raw.githubusercontent.com
records/<start>_<end>.json at the PUSHED commit — a host proven reachable
from validator egress (ToolGuard smokes) — with sha256 over the exact
file bytes. The records themselves are canonical Open-Meteo Archive
snapshots generated by scripts/generate_records.py and pushed BEFORE this
script runs.

Scenarios (expectations fixed BEFORE running; windows chosen from the
REAL generated catalog for Jakarta):
  A. drought-payout  x3 — pins over the two driest catalog weeks
     (2026-03-09..15 = 9.3 mm, 2026-05-25..31 = 9.5 mm), trigger 35 mm,
     expect PAYOUT every round (determinism: identical totals, one
     consensus round each)
  B. rain-refund     x1 — pins over two wet catalog weeks
     (2026-03-02..08 = 83.0 mm, 2026-02-02..08 = 82.2 mm), expect
     NO_PAYOUT with the premium refunded
  C. tampered-pin    x1 — second pin's digest commits to WET-window
     bytes while its URL names the dry window: digest mismatch, expect
     INCONCLUSIVE (fail-closed over valid-looking data)
Every tx: vote + exec gated (wait_final, rollback reasons surfaced);
everything appended to docs/deployment_log.json with tx hashes.
"""
import hashlib
import json
import time
import urllib.request
from pathlib import Path

from genlayer_py import create_client, create_account
from genlayer_py.chains import studionet
from genlayer_py.types import TransactionStatus

CODE_PATH = Path("contracts/rainhedge.py")
KEYFILE = Path("scripts/smoke_deployer.json")
OWNER, REPO = "faisalnugroho", "rainhedge"
# filled by scripts/pin_commit.py after the records push
PIN_COMMIT = Path("docs/pin_commit.txt").read_text().strip()
D1 = ("2026-03-09", "2026-03-15")   # 9.3 mm  (dry)
D2 = ("2026-05-25", "2026-05-31")   # 9.5 mm  (dry)
W1 = ("2026-03-02", "2026-03-08")   # 83.0 mm (wet)
W2 = ("2026-02-02", "2026-02-08")   # 82.2 mm (wet)
TRIGGER_MM = "35"
PAYOUT_PCT = 80
PREMIUM_WEI = str(10 ** 16)
COVERAGE_WEI = str(10 ** 17)
CHALLENGE = 300          # on-chain challenge window
CHALLENGE_WAIT = 320


def sha(text):
    return hashlib.sha256(text.encode()).hexdigest()


def porter_url(window):
    return ("https://raw.githubusercontent.com/" + OWNER + "/" + REPO
            + "/" + PIN_COMMIT + "/records/" + window[0] + "_"
            + window[1] + ".json")


_FILE_CACHE = {}


def live_file(window):
    """Exact bytes of the pushed record file (the same bytes validators
    fetch). Cached: commit-pinned files are immutable."""
    if window not in _FILE_CACHE:
        raw = urllib.request.urlopen(porter_url(window), timeout=60).read()
        _FILE_CACHE[window] = raw.decode("utf-8")
    return _FILE_CACHE[window]


def pin(window):
    return {"url": porter_url(window),
            "digest": sha(live_file(window))}


def pins_json(windows):
    return json.dumps([pin(w) for w in windows])


def preflight(windows):
    """sha256-check every pinned URL BEFORE burning consensus — exactly
    what validators will do."""
    for window in windows:
        text = live_file(window)
        print("preflight ok:", window, len(text), "bytes  sha",
              sha(text)[:12], flush=True)


def wait_final(client, tx_hash, label, strict=True):
    receipt = client.wait_for_transaction_receipt(
        transaction_hash=tx_hash, status=TransactionStatus.FINALIZED,
        retries=100, interval=3000)
    if isinstance(receipt, dict):
        leader = (receipt.get("consensus_data") or {}).get(
            "leader_receipt", [{}])
        lead = leader[0] if leader else {}
        exec_result = lead.get("execution_result")
        vote_result = receipt.get("result_name") or "UNKNOWN"
        if receipt.get("tx_execution_result_name") is not None:
            exec_result = receipt["tx_execution_result_name"]
        stderr = str((lead.get("genvm_result") or {}).get("stderr") or "")
        # guard-revert reasons live in leader result payload (base64-free
        # here): status=rollback + payload=reason
        rollback_reason = ""
        res = lead.get("result") or {}
        if isinstance(res, dict) and res.get("status") == "rollback":
            rollback_reason = str(res.get("payload") or "")
    else:
        exec_result, vote_result, stderr = None, "UNKNOWN", ""
        rollback_reason = ""
    ok = (exec_result in (None, "SUCCESS", "FINISHED_WITH_RETURN")
          and vote_result in ("MAJORITY_AGREE", None))
    print(f"[{label}] vote={vote_result} exec={exec_result} ok={ok}",
          flush=True)
    if not ok and strict:
        if rollback_reason:
            print("ROLLBACK REASON:", rollback_reason, flush=True)
        if stderr:
            print("STDERR tail:", stderr[-1500:], flush=True)
        raise RuntimeError(f"{label} failed: vote={vote_result} "
                           f"exec={exec_result} reason={rollback_reason}")
    return {"ok": ok, "vote": vote_result, "exec": exec_result,
            "stderr_tail": (rollback_reason or stderr[-1500:])}


def read_policy(client, addr, pid):
    raw = client.read_contract(address=addr, function_name="get_policy",
                               args=[pid])
    return json.loads(raw if isinstance(raw, str) else str(raw))


LAT, LON = "-6.2", "106.82"


def open_and_fund(client, addr, account, pid, days_json, log):
    """V3 two-sided funding: open (free) -> premium by the buyer
    (fund_policy) -> FULL coverage by a capital provider (fund_coverage).
    resolve_policy reverts coverage_not_funded without step 3."""
    tx = client.write_contract(
        address=addr, function_name="open_policy",
        args=[pid, account.address, LAT, LON, 1, TRIGGER_MM, PAYOUT_PCT,
              COVERAGE_WEI, PREMIUM_WEI, days_json, CHALLENGE],
        account=account, value=0)
    wait_final(client, tx, f"open#{pid}")
    tx = client.write_contract(
        address=addr, function_name="fund_policy", args=[pid],
        account=account, value=int(PREMIUM_WEI))
    wait_final(client, tx, f"fund#{pid}")
    tx = client.write_contract(
        address=addr, function_name="fund_coverage", args=[pid],
        account=account, value=int(COVERAGE_WEI))
    wait_final(client, tx, f"fundcov#{pid}")
    log[f"open#{pid}"] = tx


def resolve_once(client, addr, account, pid, log):
    tx = client.write_contract(
        address=addr, function_name="resolve_policy", args=[pid],
        account=account, value=0)
    wait_final(client, tx, f"resolve#{pid}")
    policy = read_policy(client, addr, pid)
    result = policy.get("result") or {}
    verdict = result.get("verdict", "UNKNOWN")
    print(f"{pid}: {verdict} totals={result.get('totals_mm')}", flush=True)
    log[pid] = {"verdict": verdict, "resolve_tx": tx,
                "totals_mm": result.get("totals_mm"),
                "labels": result.get("labels"),
                "paid_wei": policy.get("paid_wei"),
                "claimable_wei": policy.get("claimable_wei"),
                "coverage_claimable_wei": policy.get("coverage_claimable_wei"),
                "coverage_funder": policy.get("coverage_funder"),
                "result": result}
    return verdict


def v3_accounting_smoke(client, addr, account, log):
    """V3 accounting proof, chain-authoritative: after the drought
    payout the buyer must hold premium + coverage*payout_pct% and the
    FUNDER (not the buyer, not a shared pot) the exact remainder —
    proven by (a) record state, (b) the funder claiming the remainder
    via claim_coverage, (c) a second claim reverting nothing_claimable,
    (d) claim_refund from the BUYER also reverting (no premium pot
    left). Balances are read via get_policy, never inferred."""
    pid = "funder-flow"
    open_and_fund(client, addr, account, pid, pins_json([D1, D2]), log)
    print(f"[{pid}] challenge window: sleeping {CHALLENGE_WAIT}s...",
          flush=True)
    time.sleep(CHALLENGE_WAIT)
    verdict = resolve_once(client, addr, account, pid, log)
    assert verdict == "PAYOUT", verdict
    p = read_policy(client, addr, pid)
    payout = int(p["paid_wei"])
    rest = int(p["coverage_claimable_wei"])
    assert payout == int(COVERAGE_WEI) * PAYOUT_PCT // 100, payout
    assert rest == int(COVERAGE_WEI) - payout, rest
    assert int(p["claimable_wei"] or "0") == 0, p["claimable_wei"]
    # wrong-claimant guard: the buyer may NOT draw the funder's pot
    bad = client.write_contract(
        address=addr, function_name="claim_coverage", args=[pid],
        account=account, value=0)
    res = wait_final(client, bad, "claimcov#buyer-must-revert",
                     strict=False)
    p2 = read_policy(client, addr, pid)
    assert int(p2["coverage_claimable_wei"]) == rest, (
        "buyer drew the funder pot!")
    assert res["ok"] is False, "claim_coverage by buyer did NOT revert"
    log["funder_flow_guard"] = {
        "buyer_claim_tx": bad, "reverted_as_expected": True,
        "coverage_claimable_unchanged": p2["coverage_claimable_wei"]}
    # the recorded funder claims the remainder
    tx = client.write_contract(
        address=addr, function_name="claim_coverage", args=[pid],
        account=account, value=0)
    wait_final(client, tx, "claimcov#funder")
    p3 = read_policy(client, addr, pid)
    assert int(p3["coverage_claimable_wei"]) == 0, p3
    # double-claim guard: second draw must revert
    dup = client.write_contract(
        address=addr, function_name="claim_coverage", args=[pid],
        account=account, value=0)
    res2 = wait_final(client, dup, "claimcov#double-must-revert",
                      strict=False)
    assert res2["ok"] is False, "double claim_coverage did NOT revert"
    log["funder_flow"] = {
        "policy": pid, "payout_wei": payout, "funder_rest_wei": rest,
        "funder_claim_tx": tx,
        "double_claim_reverted": True,
        "buyer_claim_reverted": True}
    print("V3 funder-flow accounting: OK (payout", payout, "rest", rest,
          ")", flush=True)


def main():
    account = json.loads(KEYFILE.read_text())
    signer = create_account(account_private_key=account["private_key"])
    client = create_client(chain=studionet, account=signer)
    client.local_account = signer
    print("deployer:", signer.address, flush=True)

    log = {}
    code = CODE_PATH.read_text()
    tx = client.deploy_contract(code=code, account=client.local_account,
                                args=[], leader_only=True)
    res = wait_final(client, tx, "deploy")
    addr = res.get("contract_address")
    if not addr:
        receipt = client.wait_for_transaction_receipt(
            transaction_hash=tx, status=TransactionStatus.FINALIZED,
            retries=5, interval=3000, full_transaction=True)
        addr = (receipt.get("data") or {}).get("contract_address")
    log["deploy"] = {"tx_hash": tx, "address": addr}
    print("CONTRACT:", addr, flush=True)

    print("== preflight (canonical digests over live records) ==",
          flush=True)
    preflight([D1, D2, W1, W2])

    # A. drought determinism x3: fresh policy per run
    verdicts = []
    for i in range(1, 4):
        pid = f"drought-{i}"
        open_and_fund(client, addr, client.local_account, pid,
                      pins_json([D1, D2]), log)
        print(f"[{pid}] challenge window: sleeping {CHALLENGE_WAIT}s...",
              flush=True)
        time.sleep(CHALLENGE_WAIT)
        verdicts.append(resolve_once(client, addr, client.local_account,
                                     pid, log))
    ok_det = len(set(verdicts)) == 1 and verdicts[0] == "PAYOUT"
    print("DETERMINISM:", verdicts, "consistent:", ok_det, flush=True)

    # B. rain refund x1: pins over wet weeks
    open_and_fund(client, addr, client.local_account, "rain-1",
                  pins_json([W1, W2]), log)
    time.sleep(CHALLENGE_WAIT)
    v_b = resolve_once(client, addr, client.local_account, "rain-1", log)
    assert v_b == "NO_PAYOUT", f"rain-1 expected NO_PAYOUT got {v_b}"

    # C. tampered pin x1: pin2 digest commits to W1 (wet) canonical bytes
    #    while its URL names D2 — underwriting != measured data
    tampered = json.dumps([pin(D1),
                           {"url": porter_url(D2),
                            "digest": sha(live_file(W1))}])
    open_and_fund(client, addr, client.local_account, "tamper-1",
                  tampered, log)
    time.sleep(CHALLENGE_WAIT)
    v_c = resolve_once(client, addr, client.local_account, "tamper-1", log)
    assert v_c == "INCONCLUSIVE", (
        f"tamper-1 expected INCONCLUSIVE got {v_c}")

    # D. V3 accounting: funder-only claimable, guard reverts, claim
    v3_accounting_smoke(client, addr, client.local_account, log)

    log["results"] = {
        "determinism_consistent": ok_det,
        "verdicts": verdicts,
        "rain_refund": v_b,
        "tamper_fails_closed": v_c,
        "v3_funder_flow": log.get("funder_flow", {}),
        "windows": {"dry": [D1, D2], "wet": [W1, W2]},
        "trigger_mm": TRIGGER_MM,
        "premium_wei": PREMIUM_WEI,
        "coverage_wei": COVERAGE_WEI,
        "payout_pct": PAYOUT_PCT,
    }
    log["code_sha256_repo"] = sha(code)
    log["pin_commit"] = PIN_COMMIT
    Path("docs/deployment_log.json").write_text(json.dumps(log, indent=2))
    print("DONE. contract:", addr, flush=True)


if __name__ == "__main__":
    main()
